### PR TITLE
Fix quote highlighting issue.

### PR DESCRIPTION
**Pull request by jlewis91**
Issue where second quotation mark in double quotes is not highlighted.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Wow, nice catch!  Would you like to add some specs for this?

**Comment by jlewis91** [comment]
Specs?

**Comment by 50Wliu** [comment]
@jlewis91 https://atom.io/docs/v1.0.19/hacking-atom-writing-specs should help you a bit with understanding what specs are.  Basically they help to test against regressions and are located in the [specs](https://github.com/atom/language-sql/specs) folder.

If you still need help, you can see some other languages for examples of specs (eg https://github.com/atom/language-javascript/blob/master/spec/javascript-spec.coffee).

**Comment by C-Bouthoorn** [comment]
@jlewis91 I think you should rebase first:

```sh
git pull upstream
```

I'd like to add the specs for you after that

**Comment by MaximSokolov** [comment]
> I think you should rebase first

No need of rebasing. This branch is up-to-date.

**Comment by C-Bouthoorn** [comment]
Oh, nevermind, I was looking at his fork. Will add specs soon

**Comment by C-Bouthoorn** [comment]
Send pull request: https://github.com/jlewis91/language-sql/pull/1

**Comment by jlewis91** [comment]
@C-Bouthoorn Thanks for writing this! Sorry, have been swamped at work. :+1:

**Comment by C-Bouthoorn** [comment]
@jlewis91 GitHub says that there are still conflicts. Please run `git pull upstream` and fix the conflicts, so it can be pushed. :smile:

**Comment by jlewis91** [comment]
@C-Bouthoorn The second test you added is not related to my pull request, so I've removed it. Currently it fails:
```
    {tokens} = grammar.tokenizeLine('"Te\\"st"')
    expect(tokens[0]).toEqual value: '"', scopes: ['source.sql', 'string.quoted.double.sql', 'punctuation.definition.string.begin.sql']
    expect(tokens[1]).toEqual value: 'Te"st', scopes: ['source.sql', 'string.quoted.double.sql']
    expect(tokens[2]).toEqual value: '"', scopes: ['source.sql', 'string.quoted.double.sql', 'punctuation.definition.string.end.sql']
```
It looks like there is a reference to `#string_escape`, but I can't find where this is defined. Could this be the issue?

**Comment by C-Bouthoorn** [comment]
Ah, I see. I thought it was something with escaped quotes. Forget about the second test, that's irrelevant. As it currently passes build, and the needed tests work, I would suggest to pull it. @50Wliu

**Comment by 50Wliu** [comment]
Thanks!

**Comment by C-Bouthoorn** [comment]
You're both welcome ^^ Tag me if you're going to need more tests in the future, I'm starting to get the hang of writing them.

**Comment by jlewis91** [comment]
:+1:  :)

**Pull request merged**
